### PR TITLE
Modify to use Arduboy2 and ArduboyTones libraries

### PR DESCRIPTION
**Pull request by MLXXXp**
_audio.h_ was changed to _audio.ino_ because it contains code (and it saves having to _#include_ it).

I moved the _Sprites_ class from _ArduboyExtras_ into this sketch because the library version is dependent on the _Arduboy_ library, so caused problems with using _Arduboy2_. Plus it means one less library that the user has to install.

### CODE REVIEW

**Comment by gdmcvittie** [comment]
hmm, since the code merge, the boss's health doesn't drop, and i think the skateboarding sound isn't playing.

**Comment by MLXXXp** [comment]
I haven't looked at your code close enough to know what would cause any problems with sound. Be aware that sounds play in the background. So something like:

```
  sound.tone(250, 1000);
  delay(500);
  sound.tone(300, 1000);
```

**won't** play at 250 Hz for 1000 ms, then be silent for 500 ms, then play at 300 Hz for 1000ms.
It will start the 250 Hz tone then immediately start the 500 ms delay. After this 500 ms delay, the call for the second tone will execute, which stops the first tone and starts the second tone. So, what you get is a 250 Hz tone for 500 ms immediately followed by a 300 Hz tone for 1000 ms, with no silence in between.

If you want to wait for a tone or tone sequence to end before your code continues, you should use the _playing()_ function, like I did in your _soundGameOver()_ function.

And F.Y.I.: The _ArduboyTones_ library handles sound muting for you, so you can get rid of all the tests for _SOUND_ENABLED_. Just use `arduboy.audio.on();` and `arduboy.audio(off)` to let the user select sound on or off.

**Comment by gdmcvittie** [comment]
ah cool. i'm just comparing a few code bases, seeing where i went wrong for the other issues

**Comment by MLXXXp** [comment]
> since the code merge, the boss's health doesn't drop

I changed
`if(arduboy.everyXFrames(300)){`
to 
`if(arduboy.everyXFrames(255)){`

The value of 300 in the original would have been truncated in 8 bits to a value of 44. If this has to do with the boss's health then that might be the problem.

**Comment by gdmcvittie** [comment]
yup! thanks so much for your help man!

**Pull request merged**
